[build]
target = "aarch64-none-elf.json"

[target.'cfg(target_os = "none")']
rustflags = ["-C", "link-args= -Tlayout.ld"]
# rustflags = ["-C", "link-args= -e_start -Ttext 0x80000"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]